### ISSUE TITLE
Build fails because of glyphs having different number of segments

### ISSUE THREAD

**Issue by tplesnar** [Etcetera-Type-Co/Epilogue#19]
Hi,

I find your font extremely nice and would like to generate woff2 with some variance from the one already compiled. After installing requirements on linux and mac (having the same result on both platform), I'm getting this error

```bash
thierry@thierry-ubuntu:~/Projects/Epilogue$ make build
. venv/bin/activate; gftools builder sources/config.yaml && touch build.stamp
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/Epilogue-VF.ttf
ERROR:cu2qu.ufo:Glyphs named 'Sacutedotaccent' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'perthousand' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'gcommaaccent' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'percent' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'Otildeacute' have different number of segments
Traceback (most recent call last):
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 960, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 1040, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 331, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 540, in compileVariableTTF
    ttfDesignSpace = compileInterpolatableTTFsFromDS(
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 374, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 286, in compileInterpolatableTTFs
    glyphSets = call_preprocessor(ufos, **kwargs)
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 61, in call_preprocessor
    return preProcessor.process()
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/ufo2ft/preProcessor.py", line 289, in process
    fonts_to_quadratic(
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/cu2qu/ufo.py", line 295, in fonts_to_quadratic
    raise IncompatibleFontsError(glyph_errors)
cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs: 'Otildeacute', 'Sacutedotaccent', 'gcommaaccent', 'percent', 'perthousand'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thierry/Projects/Epilogue/venv/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 184, in build
    self.build_variable()
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 292, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/gftools/builder/__init__.py", line 329, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 711, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/home/thierry/Projects/Epilogue/venv/lib/python3.8/site-packages/fontmake/font_project.py", line 974, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'Epilogue.glyphs' -> 'master_ufo/Epilogue.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'Otildeacute', 'Sacutedotaccent', 'gcommaaccent', 'percent', 'perthousand'
make: *** [Makefile:19: build.stamp] Error 1
```

I'm not familiar with font compilation and googling the errors don't return meaningful results. Am I doing something wrong or a silent update of one tool is now breaking the compilation?

**Comment by tplesnar** [comment]
Thanks a lot @sursly !

I'm not sure I understand the file that you want me to share. I just pulled the repo on my mac, and then on my ubuntu, installed the dependencies and then run `make build` inspired by the `build.yaml` found here. https://github.com/Etcetera-Type-Co/Epilogue/blob/master/.github/workflows/build.yaml 

The only files created are during the build process. TBH, I don't need those glyphs right now, except maybe `percent` but would be glad to share a file if you tell me which one :)

**Comment by sursly** [comment]
Oh I misunderstood. I thought you made modifications and it was just not building because of that. The build situation is tricky. I'm going to ping @RosaWagner and see if she can (at her convenience) replicate your error. Leaving this issue open for sure, though.

**Comment by RosaWagner** [comment]
Hi, we have an issue with the last version of gftools (0.8.2) and transformed components. You can either have fun with decomposing transformed components in the source files, or try rebuilding but with installing gftools==0.8.0.

**Comment by sursly** [comment]
Super @RosaWagner thanks. I'll take a look at this tonight and try to make a fix for you @tplesnar 👍

**Comment by sursly** [comment]
I still can't get it to build (not good), but if all you wanted was variable woff2 files, here you go: https://github.com/Etcetera-Type-Co/Epilogue/tree/master/fonts/variable

**Comment by sursly** [comment]
Fixed the component issue and everything seems to be working ok.
